"""Add exited_while_solved column for prevent cheating while solving

Revision ID: 3d919dc5f9c0
Revises: b62e37223690
Create Date: 2025-04-05 11:47:29.850318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d919dc5f9c0'
down_revision: Union[str, None] = 'b62e37223690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('exited_while_solved', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'exited_while_solved')
    # ### end Alembic commands ###
