"""Add ability to have 2 and more sessions from different devices

Revision ID: 77c5ed87d246
Revises: 8a88027958e9
Create Date: 2025-04-03 23:56:30.191304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c5ed87d246'
down_revision: Union[str, None] = '8a88027958e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sessions_user_id_key', 'sessions', type_='unique')
    op.create_unique_constraint(None, 'sessions', ['hwid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='unique')
    op.create_unique_constraint('sessions_user_id_key', 'sessions', ['user_id'])
    # ### end Alembic commands ###
