"""Update relationships ondelete param

Revision ID: b62e37223690
Revises: 77c5ed87d246
Create Date: 2025-04-04 19:52:46.537717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62e37223690'
down_revision: Union[str, None] = '77c5ed87d246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_user_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('moves_game_id_fkey', 'moves', type_='foreignkey')
    op.create_foreign_key(None, 'moves', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rating_history_user_id_fkey', 'rating_history', type_='foreignkey')
    op.drop_constraint('rating_history_game_id_fkey', 'rating_history', type_='foreignkey')
    op.create_foreign_key(None, 'rating_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rating_history', 'games', ['game_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'rating_history', type_='foreignkey')
    op.drop_constraint(None, 'rating_history', type_='foreignkey')
    op.create_foreign_key('rating_history_game_id_fkey', 'rating_history', 'games', ['game_id'], ['id'])
    op.create_foreign_key('rating_history_user_id_fkey', 'rating_history', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'moves', type_='foreignkey')
    op.create_foreign_key('moves_game_id_fkey', 'moves', 'games', ['game_id'], ['id'])
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_user_id_fkey', 'games', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
