"""Remove 'mistakes_count' and 'exited_while_solved' field from 'game' table

Revision ID: 3df7f6272821
Revises: a23e868c38ac
Create Date: 2025-05-10 14:56:41.261207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df7f6272821'
down_revision: Union[str, None] = 'a23e868c38ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'exited_while_solved')
    op.drop_column('games', 'mistakes_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('mistakes_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('exited_while_solved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
