"""Add mistakes_count column for 'games' table

Revision ID: 75680d553cc9
Revises: 53ef3cde6865
Create Date: 2025-04-06 17:19:15.675302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75680d553cc9'
down_revision: Union[str, None] = '53ef3cde6865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('mistakes_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'mistakes_count')
    # ### end Alembic commands ###
