"""Change type to JSONB for board and solution columns in 'games' table

Revision ID: 80b14de652c3
Revises: fb36b00079a3
Create Date: 2025-04-07 09:56:22.455692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80b14de652c3'
down_revision: Union[str, None] = 'fb36b00079a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE games ALTER COLUMN board TYPE JSONB USING board::jsonb')
    op.execute('ALTER TABLE games ALTER COLUMN solution TYPE JSONB USING solution::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE games ALTER COLUMN board TYPE VARCHAR USING board::text')
    op.execute('ALTER TABLE games ALTER COLUMN solution TYPE VARCHAR USING solution::text')
    # ### end Alembic commands ###
