"""Update rating_history table

Revision ID: 8a88027958e9
Revises: 029883986e28
Create Date: 2025-04-03 22:20:03.764276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a88027958e9'
down_revision: Union[str, None] = '029883986e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_history', sa.Column('comment', sa.String(), nullable=False))
    op.alter_column('rating_history', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating_history', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rating_history', 'comment')
    # ### end Alembic commands ###
