"""Add is_valid column for 'moves' table

Revision ID: 8c461f62d06b
Revises: 75680d553cc9
Create Date: 2025-04-06 21:43:27.061315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c461f62d06b'
down_revision: Union[str, None] = '75680d553cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('is_valid', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moves', 'is_valid')
    # ### end Alembic commands ###
