"""Change default value for status column for 'games' table

Revision ID: fb36b00079a3
Revises: 8c461f62d06b
Create Date: 2025-04-06 21:52:24.534359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb36b00079a3'
down_revision: Union[str, None] = '8c461f62d06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'status',
               existing_type=sa.VARCHAR(),
               server_default='in_progress',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
